artifact_uri: /home/brunovn/Projects/mlflow_course/src/mytracks/372132989969113145/e967ff73eaab4972b79ed6c1040f7cb1/artifacts
end_time: 1754618578536
entry_point_name: ''
experiment_id: '372132989969113145'
lifecycle_stage: active
run_id: e967ff73eaab4972b79ed6c1040f7cb1
run_name: carefree-bear-8
source_name: ''
source_type: 4
source_version: ''
start_time: 1754618576963
status: 3
tags: []
user_id: brunovn
